name: Upload XoDos Release

on:
  workflow_dispatch:
    inputs:
      version_tag:
        description: 'Version tag (5.3.0)'
        required: true
        default: '5.3.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Git Tag
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git tag ${{ github.event.inputs.version_tag }}
          git push origin ${{ github.event.inputs.version_tag }}

      - name: Download Main APK
        run: |
          pip install gdown
          gdown "15bBGWXjNJ0ZG8FwTq76wzh3ZeGK3pszF" -O XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk || exit 1

      - name: Download Additional File
        run: |
          gdown "14EDDKYuuoTftTIKPJY2cy8-GxUXlDrjt" -O XoDos-ubuntu.tar.xz || exit 1

      - name: Create Release with Both Files
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version_tag }}
          name: XoDos ${{ github.event.inputs.version_tag }}
          files: |
            XoDos-${{ github.event.inputs.version_tag }}-full_arm64-v8a.apk
            XoDos-ubuntu.tar.xz
          body: | 
            New XoDos release for arm64
            What's new?
            - 
            
            For best experience download the full version APK (1.7 GB) with Bionic and Glibc wine pre-installed
            
            **Credits:**
            Team: @xodiosxðŸ‡¾ðŸ‡ª & @DevArysðŸ‡¨ðŸ‡´ & @Mondo67244ðŸ‡²ðŸ‡« & @Aurora0yðŸ‡§ðŸ‡· & @Chest1902ðŸ‡§ðŸ‡© & @jiaxinchen-max ðŸ‡¨ðŸ‡³  & @Snap888ðŸ‡·ðŸ‡º
            Logo designer: @xl_v6/ashenðŸ‡®ðŸ‡¶
            
            **Support:**
            Telegram: https://t.me/xodemulatorr
            Discord: https://discord.gg/d2ChVhPfnF
            
            Thank you for choosing XoDos by xodios M.aleiw
